name: Format PHP

on:
  pull_request:
    paths:
    - '**.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Run php-cs-fixer
      uses: docker://oskarstark/php-cs-fixer-ga

    - uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        commit_message: Apply php-cs-fixer changes
        branch: ${{ github.head_ref }}

